### ISSUE TITLE
Create a rake task that will add treats/suggestions to a user's calendar

### ISSUE THREAD

**Issue by rer7891** [TreatYoSelf/rails_be#34]
**Feature**
Create rake task that will iterate through each user and:
- [x] find open spots on their calendar that meet that time frame
- [x] find activities from their user activities that fit in those time frames
- [x] add the event with details to their calendar
- [x] test the rake task works as expected

**Comment by tyladevon** [comment]
After significant challenges with Google OAuth, team decided to icebox this functionality. Will attempt as an extension.
